-- AlterTable
ALTER TABLE "User" ADD COLUMN     "currentTier" INTEGER NOT NULL DEFAULT 1,
ADD COLUMN     "followers" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "reputation" INTEGER NOT NULL DEFAULT 10,
ADD COLUMN     "totalEarnings" DOUBLE PRECISION NOT NULL DEFAULT 0,
ALTER COLUMN "money" SET DEFAULT 100;
